### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Johana30** [rhythmictech/terraform-aws-ssm-patch-manager#22]
Error: 
```
Error: Your query returned more than one result. Please try a more specific search criteria
│ 
│   with module.patch_manager.data.aws_ssm_patch_baseline.this["WINDOWS"],
│   on .terraform/modules/patch_manager/main.tf line 1, in data "aws_ssm_patch_baseline" "this":
│    1: data "aws_ssm_patch_baseline" "this" {
```

module code:
```
module "patch_manager" {
  source  = "rhythmictech/ssm-patch-manager/aws"
  version = "~> 1.4.1"

  #log_bucket = var.log_bucket
 
  scan_schedule = "cron(0 11 ? * SAT *)"
  install_schedule = "cron(0 12 ? * SAT *)" 
    tags       = {
      OS = "WINDOWS" 
      OS = "AMAZON_LINUX_2"}
  platforms = ["AMAZON_LINUX_2", "WINDOWS"]
}
```

the maintenance windows get created when I removed (WINDOWS) from platforms, I would like to use the module to patch windows servers as well.

I have tried with the latest version, the same error.
Thanks for the help.

**Comment by sblack4** [comment]
Huh, the error says and it looks like maybe there's more than one [default](https://github.com/rhythmictech/terraform-aws-ssm-patch-manager/blob/master/main.tf#L6C26-L6C26) patch baseline for windows: https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-predefined-and-custom-patch-baselines.html 

I'm unable to reproduce the error though and running 
```
data "aws_ssm_patch_baseline" "this" {
  owner            = "AWS"
  name_prefix      = "AWS-"
  operating_system = "WINDOWS"
  default_baseline = true
}
```
returns a single patch baseline with `"name" = "AWS-DefaultPatchBaseline"`

**Comment by Johana30** [comment]
Thanks for your message.
I have created a new folder and main file now works. not sure why does not work in the old folder.

**Comment by Johana30** [comment]
Hello Sblack4, thanks for you replied.
I have fixed it.
was an issue in the system manager of the account.
Thanks

**Comment by Johana30** [comment]
working fine now
